export const validations = {
  user: {
    EMAIL_MIN_LENGTH: 6,
    EMAIL_MAX_LENGTH: 60,
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 100,
    PASSWORD_MIN_LENGTH: 6,
    PASSWORD_MAX_LENGTH: 100
  },
  vehicle: {
    REGISTRATION_NUMBER_MAX_LENGTH: 7,
    REGISTRATION_NUMBER_MIN_LENGTH: 4
  },
  trip: {
    ADDRESS_MIN_LENGTH: 2,
    ADDRESS_MAX_LENGTH: 150,
    DISTANCE_MAX_LENGTH: 10_000_000,
    COST_MAX_LENGTH: 10_000_000,
    NOTE_MAX_LENGTH: 250
  }
}
